import Link from "next/link";
import { Bell, Cpu, Flame, LogOut, Puzzle, Settings, Sparkles, Trophy } from "lucide-react";

const colors = ["bg-[#0f172a]", "bg-[#064e3b]", "bg-[#059669]", "bg-[#10b981]", "bg-[#34d399]"];
const activity = Array.from({ length: 364 }, (_, index) => {
  const value = (index * 17 + index % 9 * 7) % 20;
  return value > 17 ? 4 : value > 14 ? 3 : value > 9 ? 2 : value > 5 ? 1 : 0;
});

function Navbar() { return <header className="flex h-16 shrink-0 items-center justify-between border-b border-[#3c494c] bg-[#0c1324] px-5 md:px-8"><Link href="/" className="text-[28px] font-semibold tracking-tight text-[#8aebff]">QuantumCraft</Link><nav className="hidden h-full items-center gap-8 md:flex">{["Workspace", "Lessons", "Challenges", "Profile"].map((item) => <Link href={item === "Profile" ? "/profile" : "/"} key={item} className={`flex h-full items-center border-b-2 px-1 text-sm ${item === "Profile" ? "border-[#8aebff] text-[#8aebff]" : "border-transparent text-[#bbc9cd] hover:text-[#dce1fb]"}`}>{item}</Link>)}</nav><div className="flex items-center gap-5 text-[#bbc9cd]"><Bell size={21}/><Settings size={22}/><div className="flex h-9 w-9 items-center justify-center rounded-full border border-[#3c494c] bg-[#070d1f] text-[#8aebff]">◉</div></div></header>; }
function Stat({ icon: Icon, label, value, color }) { return <div className="border border-[#1e293b] bg-[#0f172a] p-6 transition hover:bg-[#151b2d]"><div className="mb-4 flex items-center gap-3 text-[#bbc9cd]"><Icon size={23} className={color}/><h2 className="text-[12px] font-semibold tracking-[0.1em]">{label}</h2></div><p className="text-[28px] text-[#dce1fb]">{value}</p></div>; }
function Heatmap() { return <div className="flex min-w-max gap-1">{Array.from({ length: 52 }, (_, week) => <div className="flex flex-col gap-1" key={week}>{activity.slice(week * 7, week * 7 + 7).map((level, day) => <div key={day} title={level ? "Active" : "Inactive"} className={`h-[11px] w-[11px] rounded-[2px] ${colors[level]}`}/>)}</div>)}</div>; }
export default function ProfilePage() { return <div className="flex min-h-screen flex-col bg-[#020617] font-sans text-[#dce1fb]"><Navbar/><main className="mx-auto flex w-full max-w-[1440px] flex-1 flex-col gap-10 px-6 py-10 md:px-10"><section className="relative flex flex-col items-center gap-8 overflow-hidden border border-[#1e293b] bg-[#0f172a] p-8 md:flex-row"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(47,217,244,0.12),transparent_55%)]"/><div className="relative flex h-36 w-36 shrink-0 items-center justify-center rounded-full border-2 border-[#8aebff] bg-[#070d1f] text-center text-4xl text-[#8aebff] shadow-[0_0_20px_rgba(47,217,244,0.3)]">◉</div><div className="relative text-center md:text-left"><h1 className="text-4xl font-semibold tracking-[-0.05em] text-[#dce1fb] md:text-5xl">Quantum Explorer</h1><div className="mt-3 inline-flex items-center gap-2 rounded-full border border-[#8aebff] bg-[#8aebff]/10 px-4 py-1 text-xs font-semibold tracking-wide text-[#8aebff]"><Sparkles size={14}/> Quantum Rank: Intermediate</div></div><button className="relative ml-auto flex items-center gap-2 border border-[#3c494c] px-4 py-3 text-sm hover:bg-white/5"><LogOut size={20}/> Logout</button></section><section className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={Flame} label="CURRENT STREAK" value="5 Days" color="text-[#8aebff]"/><Stat icon={Puzzle} label="CHALLENGES SOLVED" value="12" color="text-[#ddb7ff]"/><Stat icon={Cpu} label="QUBIT OPERATIONS" value="340" color="text-[#22d3ee]"/><Stat icon={Trophy} label="TOTAL XP" value="2450" color="text-[#ffaaaf]"/></section><section className="border border-[#1e293b] bg-[#0f172a] p-6"><h2 className="mb-7 border-b border-[#1e293b] pb-3 text-[25px] tracking-tight">Activity Contribution</h2><div className="overflow-x-auto pb-3"><Heatmap/></div><div className="mt-5 flex items-center justify-end gap-2 font-mono text-xs text-[#bbc9cd]"><span>Less</span>{colors.map((color) => <i key={color} className={`h-3 w-3 rounded-[2px] ${color}`}/>)}<span>More</span></div></section></main></div>; }
